version: '3'
services:
  app:
    container_name: go_fiber
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    ports:
      - 5000:5000
    restart: on-failure
    environment:
      - PORT=5000
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=go-fiber
